services:
  voxwave:
    build: .
    image: voxwave:latest
    container_name: voxwave
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
